### ISSUE TITLE
quick fix is not available

### ISSUE THREAD

**Issue by hjiog** [xojs/vscode-linter-xo#109]
![image](https://user-images.githubusercontent.com/42141272/144158399-fb5bd324-82fa-41ca-9c44-3bf0db4e6384.png)

**Comment by Spence-S** [comment]
We currently only provide quick fixes that are also able to be fixed by xo --fix. This is not a fixable error fro what I can see here, and therefore should not have a quick fix. Quick fix seems to work fine for me.
