### ISSUE TITLE
Provides links to @typescript-eslint rules

### ISSUE THREAD

**Issue by gutenye** [xojs/vscode-linter-xo#112]
As shown below, the Eslint extension provides a link to the rule `@typescript-eslint/no-empty-function`, but not with XO extension. 

<img width="1054" alt="Screen Shot 2022-05-06 at 20 00 54" src="https://user-images.githubusercontent.com/377544/167127540-7303852a-f5f4-42c2-9b1d-188121fd6128.png">

**Comment by Spence-S** [comment]
both xo and this extension rely on https://github.com/stefanbuck/eslint-rule-docs for these links. 

Opened a related issue here https://github.com/stefanbuck/eslint-rule-docs/issues/5

**Comment by Spence-S** [comment]
As of xo release v0.51.0 and v3.10.0 of this extension, xo natively finds rule docs and the extension support showing them. For earlier versions of xo, eslint-rule-docs will be used as a fallback. Upgrade xo to latest version to always have correct docs now.
