### ISSUE TITLE
Adding a `.eslintignore` file causes erroneous parsing errors in VSCode

### ISSUE THREAD

**Issue by droobertzka** [xojs/vscode-linter-xo#114]
## What?

Adding an `.eslintignore` file results in the vscode-linter-xo extension not correctly using the babel eslint parser and throwing parsing errors such as the following on otherwise non-problematic javascript files:
> Parsing error: the keyword 'import' is reserved

This is true despite including `engines` in package.json and is not specific to any particular keyword (i.e. if using commonjs `require()`s with unicorn/prefer-modules turned off, it will error on the `const` keyword). 

This error is specific to the `vscode-linter-xo` extension and does not show up in `xojs/xo`.

## Repro Steps

I created a repo with branches to illustrate [my observations](https://github.com/droobertzka/xo-eslintignore-test).  

## Observations

You may need to close the VSCode window and reopen it when switching branches.

- Everything is as expected before a eslintignore file is created
  - see `main` branch
- Adding a eslintignore file results in unexpected parsing errors in VSCode, but `npx xo` works fine and respects the ignores
  - see `eslintignore` branch 
- Adding a eslintrc file with the parsing engine explicitly set to `@babel/eslint-parser` fixes the parsing errors
  - see `eslintconfig` branch
- Using an `.xo-config.js` to set the ignores does not result in the parsing errors in VSCode
  - see `xoconfig` branch

## Environment Details
- **samverschueren.linter-xo:** v3.9.0
- **xojs/xo** v0.49.0 and v0.42.0 - (latest at time of testing and version in the project I originally noticed this in, respectively)
- **engines (in package.json):**
  - "node": ">=14.0.0 <15.0.0",
    "npm": ">=8.3.0 <9.0.0"
- **VSCode:** v1.67.2
  - Version: 1.67.2
  - Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
  - Date: 2022-05-17T18:20:57.384Z
  - Electron: 17.4.1
  - Chromium: 98.0.4758.141
  - Node.js: 16.13.0
  - V8: 9.8.177.13-electron.0
  - OS: Darwin x64 21.5.0
- **Node & NPM:**
  - node v14.19.1
  - npm v8.7.0
- **macOS:** Monterey 12.4
- **MacBook Pro:** (16-inch 2019)

## Thank you!

I love what you all have done with XO and this extension. Thank you so much. Cheers!

**Comment by Spence-S** [comment]
Thanks for the detailed report, unfortunately, I could not reproduce after following all of the steps. Behavior for me was consistent and predictable. I tried reproducing with both node 14 and 16. 

Further, this extension nor xo cli interact with eslintignore at all, that is handled entirely by eslint, which is what xo uses under the hood. This extension, nor the xo cli, can use an eslint config file directly, and i believe the way we pass the data to eslint, i don't believe it will search for a config either, so adding an eslint config should have no effect.

One thing I did notice is that your node version and vscode are using different node binaries, make sure you have the xo.runtime setting set to ensure you have consistent results across vscode and the cli.

May be worth trying to reproduce your problem on an instance of vscode with no other extensions _except_ the xo extension installed and letting me know if you have the same issue.
