### ISSUE TITLE
Configuration for rule "@typescript-eslint/unified-signatures" is invalid

### ISSUE THREAD

**Issue by jdbruijn** [xojs/vscode-linter-xo#115]
With xo 0.50.0 I'm getting the following error. Reverting to 0.48.0 (the one that I was previously using) the error disappears again.

> BaseConfig » /Users/jdbruijn/work/projects/dtls-termination-proxy/node_modules/xo/node_modules/eslint-config-xo-typescript/index.js: Configuration for rule "@typescript-eslint/unified-signatures" is invalid: Value [{"ignoreDifferentlyNamedParameters":true}] should NOT have more than 0 items.

- Extension v3.9.0
- xo v0.50.0
- Visual Studio Code
  ```
  Version: 1.68.1 (Universal)
  Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
  Date: 2022-06-14T12:52:13.188Z
  Electron: 17.4.7
  Chromium: 98.0.4758.141
  Node.js: 16.13.0
  V8: 9.8.177.13-electron.0
  OS: Darwin x64 21.5.0
  ```
- system
  ```
  System:
    OS: macOS 12.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 29.92 MB / 8.00 GB
    Shell: 5.8.1 - /usr/local/bin/zsh
  Binaries:
    Node: 18.4.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.13.1 - ~/work/projects/dtls-termination-proxy/node_modules/.bin/npm
    ```

**Comment by Spence-S** [comment]
This should be open in the `xo` repo and not here.
