### ISSUE TITLE
Add a command to restart XO server

### ISSUE THREAD

**Issue by kidonng** [xojs/vscode-linter-xo#117]
There are times when a change does not take effect immediately (e.g. modifying `tsconfig.json`) or XO stuck at a previous state, restarting XO server may come in handy. Currently I have to search and kill the process myself, which is inconvenient.

Ideally we should have a `XO: restart server` command similar to `TypeScript: Restart TS Server`.

**Comment by Spence-S** [comment]
I agree, I can add this command in the next release. As a workaround I use the command: `Developer: reload window` for this kind of thing a lot.

**Comment by kidonng** [comment]
That's... a last resort. I treat it as a kill switch when something goes wrong and I can't/don't want to figure out how to reset it. I also use Codespaces a lot and reloading window will cause a reconnection and mess up my terminal.

**Comment by Spence-S** [comment]
Added in the latest release
