### ISSUE TITLE
Extension does not work with untitled files and files opened outside of folders

### ISSUE THREAD

**Issue by kidonng** [xojs/vscode-linter-xo#118]
When writing in Untitled files (i.e. new files not saved to disk), XO prompts an error with every keystroke:

```
Cannot read properties of undefined (reading 'length')
```

It would be awesome if the extension can support or at least disable for them.

**Comment by kidonng** [comment]
Actually it's not just untitled files, it's any file opened outside of a folder. This seems to be the same as #108, so the extension does support it but it's broken now.

**Comment by Spence-S** [comment]
@kidonng regarding untitled/unsaved files, this may not be something we will pursue.

This extension always uses the _users_ xo (and any corresponding configs) to lint things, so untitled files are a grey area there. 

The architecture of the extension is changing to attempt to resolve xo up from wherever the file is everytime, so it won't be dependant on being a file in the vscode workspace anymore which I think will be a close solution. It will still require that the users `xo` can be found upstream from the file.  I will leave this issue open until the new architecture is released.

**Comment by Spence-S** [comment]
This should be resolved with the latest release
