### ISSUE TITLE
"xo: Fix all auto-fixable problems" not working. Logging: Cannot read properties of undefined (reading 'protocol2CodeConverter')

### ISSUE THREAD

**Issue by lucafo741** [xojs/vscode-linter-xo#121]
The "Fix all auto-fixable problems" command ain't working for me.
On the "Runtime Status" there's this `Cannot read properties of undefined (reading 'protocol2CodeConverter')` error logged for each try.

**Comment by Spence-S** [comment]
closed by 89702e2e18bc6ece22425d149fe2a121add8cb80
