### ISSUE TITLE
Failed to load plugin 'unicorn' declared in 'BaseConfig'

### ISSUE THREAD

**Issue by mhenke** [xojs/vscode-linter-xo#127]
Version: 1.62.2 (system setup)
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:56:38.428Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
samverschueren.linter-xo

![image](https://user-images.githubusercontent.com/119844/208497962-818b0332-e51d-429c-b0c2-10962eddc4d2.png)

[Error - 12:38:49 PM] Failed to load plugin 'unicorn' declared in 'BaseConfig » c:\Users\igem173\angular-workspace\106801_shipment_dashboard\node_modules\xo\config\plugins.cjs': Cannot find module 'node:path'
Require stack:
- c:\Users\igem173\angular-workspace\106801_shipment_dashboard\node_modules\xo\node_modules\eslint-plugin-unicorn\rules\utils\rule.js
- c:\Users\igem173\angular-workspace\106801_shipment_dashboard\node_modules\xo\node_modules\eslint-plugin-unicorn\index.js
- c:\Users\igem173\angular-workspace\106801_shipment_dashboard\node_modules\@eslint\eslintrc\dist\eslintrc.cjs
Referenced from: c:\Users\igem173\angular-workspace\106801_shipment_dashboard\node_modules\xo\config\plugins.cjs

**Comment by spence-s** [comment]
I think this is a cli bug. Not enough info here. -- please confirm this error does not occur with the cli and re-open if needed.
