### ISSUE TITLE
[bug] displays lint errors in `node_modules` files that use `xo`

### ISSUE THREAD

**Issue by tommy-mitchell** [xojs/vscode-linter-xo#131]
If a given package uses `xo` (listed in their (dev-)dependencies), the extension will lint them:

<details>
<summary>Large screenshot</summary>

<img width="787" alt="image" src="https://user-images.githubusercontent.com/1403701/230469208-70080d75-1c2d-4c4a-9642-dd4d764db862.png">

</details>

This can make inspecting some packages unreadable. In addition, if `xo` is setup to format on save, any userland modifications to a package causes the extension to try formatting them.

**Comment by spence-s** [comment]
v3.16.0 removes the ability for this extension to lint in the node_modules folder - if someone would like this ability, leave a comment and we can put it behind an option.
