### ISSUE TITLE
Uncaught Errors

### ISSUE THREAD

**Issue by simwai** [xojs/vscode-linter-xo#132]
Type: <b>Bug</b>

Just programmed a simple TS or Node.js project. Don't know more about it. 

Extension version: 3.14.1
VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.18GB free)|
|Process Argv|--folder-uri file:///d%3A/Downloads/GitHub/ai-sentiment-report --crash-reporter-id 881b0b48-3029-43cf-8afa-a8e878cdd0ef|
|Screen Reader|no|
|VM|67%|
</details>

**Comment by spence-s** [comment]
This bug report is not helpful or actionable

**Comment by simwai** [comment]
How would i be able to create a helpful record?
