### ISSUE TITLE
Use inside a devcontainer is slow and do not reset errors

### ISSUE THREAD

**Issue by vabatta** [xojs/vscode-linter-xo#133]
Using the extension inside a [devcontainer](https://code.visualstudio.com/docs/devcontainers/create-dev-container) is slow and do not reset errors.
With the following config
```json
"xo": {
	"extends": "xo-react",
	"prettier": true,
	"envs": [
		"es2024",
		"webextensions",
		"browser"
	]
}
```

Editing a simple file (trimmed for sake of example)
```jsx
return (
	<Theme>
		<Heading>
			Welcome to your{' '}
			<a href="https://www.plasmo.com" target="_blank" rel="noreferrer">
				Plasmo
			</a>{' '}
			Extension!
		</Heading>
	</Theme>
);
```

As soon as I delete part of `</Heading>`, I get the error `Parsing error: Expected corresponding JSX closing tag for 'Heading'.XO` but it won't reset if I complete it again. A server resets makes the error go away. (To clarify, I get the error while the code is valid)

**Comment by spence-s** [comment]
There isn't much we can do about performance here: try the tricks here and see if you can up your container resources or move your files inside the container.

https://code.visualstudio.com/remote/advancedcontainers/improve-performance

I personally do not use dev containers and have no interest in trying them, so I won't be testing against them, if you find something obvious that we are doing to not support them, feel free to make a PR, but nothing stands out to me in the documentation. 

I have never had a good experience using docker desktop or docker at all on mac so I generally avoid.
