### ISSUE TITLE
[bug] quick fixes no longer shown through keyboard

### ISSUE THREAD

**Issue by tommy-mitchell** [xojs/vscode-linter-xo#137]
After updating to the latest release, open the Quick Fix menu through the keyboard (e.g. with <kbd><kbd>CMD</kbd> + <kbd>.</kbd></kbd>) no longer shows fixes from `xo`. The correct behavior still works from hover/mouse:

<details>
<summary>Via keyboard</summary>

<img width="541" alt="quick-fix-keyboard" src="https://github.com/xojs/vscode-linter-xo/assets/1403701/295e4b78-e576-480c-8488-b310ec205604">

</details>

<details>
<summary>Via mouse</summary>

![quick-fix-mouse](https://github.com/xojs/vscode-linter-xo/assets/1403701/4ecd589a-befd-4059-9ff6-f79cef4aaa52)

</details>

**Comment by spence-s** [comment]
closed by v3.18.1

**Comment by tommy-mitchell** [comment]
Thanks for the quick fix @spence-s :) just gotta say, the updated quick fix titles are immediately more readable!

I'm also not sure if it's been reported before, but "insert same line" adds an extra space before the comment. I can open an issue if it hasn't been.

**Comment by spence-s** [comment]
thanks @tommy-mitchell this is something I didn't notice - but I opened a bug - I should be able to get this taken care of soon!

https://github.com/xojs/vscode-linter-xo/issues/138
