### ISSUE TITLE
[bug] `import/no-extraneous-dependencies` does not refresh when new dependencies are added

### ISSUE THREAD

**Issue by tommy-mitchell** [xojs/vscode-linter-xo#140]
After installing a new dependency, I have to restart the XO linter to satisfy `import/no-extraneous-dependencies`:

![image](https://github.com/xojs/vscode-linter-xo/assets/1403701/d2163cb7-8cd7-4128-a483-24455417ec24)

**Comment by spence-s** [comment]
This should be fixed as of v3.20.0
