### ISSUE TITLE
[Feature Request] Restart server on config change

### ISSUE THREAD

**Issue by lachieh** [xojs/vscode-linter-xo#143]
I've noticed that changing settings in the config means a restart of the server is required to see the changes. It would be good to watch the following files in all subfolders and restart the server automatically on save:

- `package.json`
- `tsconfig.json`
- `.xo-config`
- `xo-config.json`
- `.xo-config.js`
- `xo.config.js`
- `.xo-config.cjs`
- `xo.config.cjs`

This would also have the benefit of resolving #140 because a change to the the dependencies in the `package.json` would also trigger a refresh.

**Comment by lachieh** [comment]
Understood. Thanks for the insight. Feel free to close this issue and track on one of the others 👍🏻 thanks again.

Perhaps a setting to change the watch behavior would be beneficial. i.e. `restart server`, `reload config` or `manual/off`. That way users who have slower machines can select one of the lighter options if they experience performance issues.

**Comment by spence-s** [comment]
Ok  in v3.20.0 we restart the server and that should fix all of these problems. If it ends up being a problem well add the option back in for faster restarts for at least the json configurations.
