### ISSUE TITLE
Action to add ignore to a line

### ISSUE THREAD

**Issue by wmertens** [xojs/vscode-linter-xo#16]
It would be cool if you could run an action to automatically ignore the current offending rule for the line (or file).

So if you have to use some older API and it has snake_case on a line, causing a violation of `camelcase`, you can run the action and it would add `// eslint-disable-line camelcase` to that line.

**Comment by SamVerschueren** [comment]
Nice suggestion!

**Comment by Spence-S** [comment]
Done v3.14.1
