### ISSUE TITLE
'Fix all auto-fixable problems' doesn't fix as many issues as possible

### ISSUE THREAD

**Issue by xlc** [xojs/vscode-linter-xo#42]
Same issue as https://github.com/Microsoft/vscode-eslint/issues/154

If there are multiple fixes, xo.fix command doesn't always fixes all of them. Sometimes it is required to run it multiple times to fix all the issues.

Potential solution:
Add a new xo.fixAll command that run the xo.fix command multiple times until no more fix was applied.

Reference:
https://github.com/Microsoft/vscode-eslint/issues/154#issuecomment-312415466
https://github.com/eslint/eslint/blob/13971798c4017245cbdf9913680c069edefbfe6b/lib/linter.js#L1110

**Comment by SamVerschueren** [comment]
I also noticed this with the TSLint extension, but to be honest I never had this with the XO one. Do you know when it starts failing? After X number of fixes? I read the `vscode-eslint` topic but not the ones linked in there.

**Comment by xlc** [comment]
I never fully worked. It only apply one iteration of the fix which doesn't always fixes all the issues.
One example code is `var a = 1` with rule prefer const and require semi, it takes multiple iterations to make it `const a = 1;`

**Comment by jopdeklein** [comment]
A bit late to the party, but I can confirm in some cases multiple format actions are needed to get the desired result, see attached gif. If I run XO directly from the CLI it formats correctly so it seems related to this plugin, not XO itself.

![xo_fast](https://user-images.githubusercontent.com/200943/100265840-24baa400-2f51-11eb-97c9-03bd8fff33c9.gif)
