### ISSUE TITLE
Relative paths in extends config seem to be broken in 2.2.1

### ISSUE THREAD

**Issue by nopelluhh** [xojs/vscode-linter-xo#47]
It looks like this [this commit/line](https://github.com/SamVerschueren/vscode-linter-xo/commit/4c7c6a140658394e58d6d9c5aec694b1939d9589#diff-bc3c0f2fe3aca9ddbe96347ffb00641eR20) is causing a relative path to a config to break.

Example package.json config which worked on previous versions:
```
{
  ...
  "xo": {
    "extends": [
      "xo-react",
      "./my-special-config-with-imported-resolvers.js"
    ],
  ...
}
```

Is this an intentional change/any suggestions for how to get around this?

**Comment by SamVerschueren** [comment]
Mmm, weird. I was refactoring some bits and fought I needed it for [this change](https://github.com/SamVerschueren/vscode-linter-xo/commit/4c7c6a140658394e58d6d9c5aec694b1939d9589#diff-bc3c0f2fe3aca9ddbe96347ffb00641eR19). I was looking into the ESLint extension as they do it the exact same way. Can you give a quick small example of such a resolver file so I can test more easily?

**Comment by nopelluhh** [comment]
Here you go! Again, not sure if there's an alternate way around this, but it was working previously. There's a bit of a cascade of plugins from xo -> eslint -> eslint-import-resolver-webpack, but I think the scenario of an local config is more universal. In this case it's in use for webpack aliases on a large project.  

```
const  { join } = require('path')
module.exports = {
  {
  settings: {
      'import/resolver': {
        webpack: {
          config: join(__dirname, 'webpack.config.dev.js')
        }
      }
    }
  }
}
```

**Comment by xlc** [comment]
https://github.com/xlc/vscode-linter-xo/blob/5e7392ecbe63925e62411529dc578688ab2bc9f7/server/src/linter-server.ts#L253
This could fix it. I have no idea why it is needed and by eslint extension doesn't require it. But some code is caching the cwd on resolve time instead of check time

**Comment by SamVerschueren** [comment]
I will try to reproduce it and see if that fix works. Help welcome for this :).

**Comment by SavageCore** [comment]
Same issue here I believe:

```

**Comment by SavageCore** [comment]
Same issue here when using xo.settings in package.json so not just extends? Or is this a separate issue I'm facing?

`xo` command returns no errors but vscode will report `import/no-unresolved` for a path such as `const {ModelsLoader} = require('src/infra/sequelize');`

`package.json:`
```
  "xo": {
   ...
    "settings": {
      "import/resolver": {
        "node": {
          "paths": [
            "."
          ]
        }
      }
    }
  }
```

`directory tree:`
```
src
src/infra/sequelize
src/infra/sequelize/index.js
src/infra/sequelize/models-loader.js
package.json
```

**Comment by yakov116** [comment]
@idmyn are you still having an issue with the latest version?

**Comment by Spence-S** [comment]
stale
