### ISSUE TITLE
[XO] Test file is ignored because it is not in Test file is ignored because it is not in `test.js test-*.js test/**/*.js **/__tests__/**/*.js **/*.test.js`

### ISSUE THREAD

**Issue by 07Gond** [xojs/vscode-linter-xo#54]
**BUG:** 

![image](https://user-images.githubusercontent.com/2708687/45393672-a503c180-b5f2-11e8-9136-a5e9e8009c99.png)

**NOTES:**

- When I run `npx xo` in the CLI or my test script I don't have any issue.
- My only test file name: **_index.test.js_** inside **_tests_** directory

_package.json:_
```json
"scripts": {
		"test": "xo && ava --verbose",
		"coverage": "nyc yarn test"
	},
	"ava": {
		"files": [
			"tests/**/*.test.js"
		]
	},
```

**Additional Info:**
**OS**: Mac OS 10.13.6

**Comment by 07Gond** [comment]
Hi @SamVerschueren any idea on this issue?
It is a little annoying see this on the code 😞

**Comment by OmgImAlexis** [comment]
Still having this issue.

**Comment by OmgImAlexis** [comment]
I'm also having this issue.

**Comment by yakov116** [comment]
@07Gond are you still having an issue?

**Comment by Spence-S** [comment]
stale
