### ISSUE TITLE
Parsing error: The keyword 'interface' is reserved on d.ts file

### ISSUE THREAD

**Issue by niktekusho** [xojs/vscode-linter-xo#60]
First, some env info (taken from VS Code):

```
Version: 1.30.1 (system setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Data: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134
```

XO-specific info:
```
xo: 0.23.0
samverschueren.linter-xo: 2.3.2
```

Now to the problem.

I noticed that with xojs/xo#348 `xo` did indeed have problems with typescript files.
So from what I gathered in that issue the linting for ts files has been disabled.
And indeed running `$ npx xo` on the project yields no errors (the `*.d.ts` file **seems** (to me) ignored from linting).
But this extension really likes typescript files, so it tries to lint it regardless 😆.

Searching for issues of a similar kind, I found that the solution provided in #53 works for me too.

For reference, in the `package.json` file I added the following snippet (I have a single typescript definition file):

```json
    "xo": {
        "ignores": [
            "*.d.ts"
        ]
    }
```

Finally, the question: could the extension ignore typescript files just as the xo CLI seems to do?

*FWIW I may be thinking the wrong thing on the xo CLI of course.*

If you need a repository for reproducing the "error", feel free to ask me and I'll gladly provide you the one I am using.

**Comment by yakov116** [comment]
@niktekusho are you still having an issue?

**Comment by Spence-S** [comment]
stale
