### ISSUE TITLE
`Format Selection` not using xo

### ISSUE THREAD

**Issue by mamachanko** [xojs/vscode-linter-xo#66]
Big thanks for the plugin!

I have configured it like so:
```js
{
  // ...
  "xo.enable": true,
  "xo.format.enable": true
}
```

When I `Format Document` the whole document gets formatted complying with my `xo` config. However, when I `Format Selection` then it gets formatted according according VS Code defaults.

**Comment by lxghtless** [comment]
Try something like this in your `settings.json`?

```json
{
	"xo.enable": true,
	"xo.format.enable": true,
	"[json]": {
		"editor.formatOnSave": true,
		"editor.defaultFormatter": "esbenp.prettier-vscode"
	},
	"[typescript]": {
		"editor.formatOnSave": true,
		"editor.defaultFormatter": "samverschueren.linter-xo"
	}
}
```

**Comment by yakov116** [comment]
Looks like your settings are not correct.

Issue can be closed
