### ISSUE TITLE
Problem on Windows with Yarn Workspaces

### ISSUE THREAD

**Issue by shanoaice** [xojs/vscode-linter-xo#77]
I uses Yarn Workspaces together with XO, and when I perform installation from WSL, the extension Linter XO will give an error like this:

```
UNKNOWN: unknown error, lstat 'd:\eslint-tools\node_modules\eslint-chain'
```

My directory structure are like this:
```
.
├── eslint-chain
│   ├── LICENSE
│   ├── README.md
│   ├── package.json
│   ├── src
│   │   └── index.ts
│   └── tsconfig.json
├── package.json
└── yarn.lock
```

When I perform the installation from the Windows side, nothing happens. I suppose this relates to how Linux links directory.

**Comment by yakov116** [comment]
@shanoaice still have an issue?

**Comment by Spence-S** [comment]
stale
