### ISSUE TITLE
Import the globally installed version if XO is not locally installed

### ISSUE THREAD

**Issue by glossnyx** [xojs/vscode-linter-xo#79]
I want to use XO with my [Deno] project, which almost works perfectly, except this extension requires `xo` to be listed in `package.json`. Deno doesn't use `package.json`, so I have to make a couple of new files just to get XO working.

Here is my current workaround, but as you can see, it's very messy and it would be much cleaner if this extension could use the global installation natively.

`package.json`:

```json
{
  "devDependencies": {
    "xo": "file:.xo.js"
  }
}
```

`.xo.js`:

```js
module.exports = require("xo");
```

Edit: looking back at older issues, it is probably a good idea to add a new option in the VSCode settings that determines if the extension should check for globally-installed versions, just in case you don't want to use XO in a specific project but you have it globally installed.

[Deno]: https://deno.land

**Comment by darkred** [comment]
Just wanted to mention that since [v0.41.0](https://github.com/xojs/xo/releases/tag/v0.41.0) :
> XO can no longer be installed globally.
> It caused too many problems. Instead, you can run the local XO binary with `$ npx xo`.

**Comment by Spence-S** [comment]
@darkred thanks - I was still thinking of supporting this since it seemed really easy to do... After further thought, I'm not really sure if the use case is valid or not or if it would cause dependency resolution problems. 

I don't use deno. @glossnyx is this something this is still desired in the deno community??

**Comment by glossnyx** [comment]
I wouldn't know, I don't use deno/xo anymore.

**Comment by Spence-S** [comment]
ok - after thought and seeing that this was the only request for this feature, im going to remove this from the roadmap as it doesn't seem useful enough and isn't inline with the xo philosophy.
