### ISSUE TITLE
Only underlines the first character of a lint error

### ISSUE THREAD

**Issue by osdiab** [xojs/vscode-linter-xo#87]
ESLint VSCode plugin underlines the whole error, this one only underlines the first character, which makes it annoying to hover.

![Screen Shot 2021-02-09 at 20 45 07](https://user-images.githubusercontent.com/1890926/107359213-c6e13580-6b17-11eb-936e-c3ff869281f2.png)
![Screen Shot 2021-02-09 at 20 30 53](https://user-images.githubusercontent.com/1890926/107359218-c8126280-6b17-11eb-8b4c-d4d7f23da493.png)

**Comment by yakov116** [comment]
@osdiab I do not see this issue with the latest version of xo and this plugin. Please report if you still have this issue.

**Comment by osdiab** [comment]
We can close it - I haven't been using XO anymore because of it's lack of support, hopefully the situation gets better with the new roadmap I saw!

**Comment by Nicholaiii** [comment]
I have this issue, everywhere.
![image](https://user-images.githubusercontent.com/7280931/144220849-87301492-4d0e-4dff-8917-a764a20329cf.png)

**Comment by Spence-S** [comment]
Yep - this is annoying and have been meaning to fix this - will make this a priority to have soon.
