### ISSUE TITLE
Doesn't format with `editor.formatOnSaveMode` set to `modifications`

### ISSUE THREAD

**Issue by zardoy** [xojs/vscode-linter-xo#97]
XO works okay as formatter, but not with `editor.formatOnSaveMode` set to `modifications` setting.

VSCode says: Extension 'XO' cannot format 'file'.

It's would be handy for me, because I got used to it with ESLint and noticed it saved some extra time on saving big TS files (but I might be wrong).

**Comment by Spence-S** [comment]
Currently this isn't supported but it's a great idea, we will add it to the roadmap.

**Comment by Spence-S** [comment]
This is now support in the 3.14 release
